# configs/imagebind_mlp.yaml
name: imagebind_mlp

params:
  # ğŸ”¹ Vision æ¨¡æ€
  vision_embed_dim: 1280
  vision_num_blocks: 32
  vision_num_heads: 16

  # ğŸ”¹ Text æ¨¡æ€
  text_embed_dim: 1024
  text_num_blocks: 24
  text_num_heads: 16

  # ğŸ”¹ è¾“å‡ºç»´åº¦
  out_embed_dim: 1024

  # ğŸ”¹ Drop Path è¶…å‚
  audio_drop_path: 0.1
  imu_drop_path: 0.7

  # 
  extra_params:
    input_dim: 1024
    hidden_dim: 512
    dropout_p: 0.1
